# Generated by Django 2.1.4 on 2019-07-27 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование категории')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_req.CategoryReq', verbose_name='Подкатегория')),
            ],
        ),
        migrations.CreateModel(
            name='ManagingOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField(blank=True, null=True, verbose_name='ID Управляющей организации на Портале')),
                ('subject_rf', models.CharField(default='', max_length=200, verbose_name='Субъект РФ')),
                ('name_full', models.CharField(default='', max_length=200, verbose_name='Фирменное наименование юр лица')),
                ('name_short', models.CharField(default='', max_length=200, verbose_name='Сокращенное наименование')),
                ('name_employee', models.CharField(default='', max_length=200, verbose_name='ФИО руководителя')),
                ('inn', models.CharField(default='', max_length=200, verbose_name='ИНН')),
                ('ogrn', models.CharField(default='', max_length=200, verbose_name='ОГРН')),
                ('legal_address', models.CharField(default='', max_length=200, verbose_name='Адрес юридического лица')),
                ('phone', models.CharField(default='', max_length=200, verbose_name='Адрес фактического местонахождения органов управления')),
                ('actual_address', models.CharField(default='', max_length=200, verbose_name='Телефон')),
                ('fax', models.CharField(default='', max_length=200, verbose_name='Факс')),
                ('email', models.CharField(default='', max_length=200, verbose_name='Адрес электронной почты')),
                ('site', models.CharField(default='', max_length=200, verbose_name='Официальный сайт ')),
                ('count_mkd', models.CharField(default='', max_length=200, verbose_name='Количество домов, находящихся в управлении')),
                ('area_total', models.CharField(default='', max_length=200, verbose_name='Площадь домов, находящихся в управлении')),
                ('w_summ', models.CharField(default='', max_length=200, verbose_name='Присвоенный рейтинг на дату выгрузки')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[(1, 'В обработке'), (2, 'В работе'), (3, 'На доработке'), (4, 'Выполнена')], default=1, max_length=200, null=True)),
                ('text', models.CharField(default='', max_length=1000, verbose_name='Текст запроса')),
                ('date_req', models.DateField(auto_now_add=True, null=True, verbose_name='Время последнего изменения заявки')),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_req.CategoryReq', verbose_name='CategoryInfo')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField(blank=True, null=True, verbose_name='ID дома на Портале')),
                ('region_id', models.IntegerField(blank=True, null=True, verbose_name='Субъект РФ (код ФИАС)')),
                ('area_id', models.IntegerField(blank=True, null=True, verbose_name='Район (код ФИАС)')),
                ('city_id', models.IntegerField(blank=True, null=True, verbose_name='Населенный пункт (код ФИАС)')),
                ('street_id', models.IntegerField(blank=True, null=True, verbose_name='Улица (код ФИАС)')),
                ('shortname_region', models.CharField(default='', max_length=200, verbose_name='Тип Субъекта РФ')),
                ('formalname_region', models.CharField(default='', max_length=200, verbose_name='Субъект РФ')),
                ('shortname_area', models.CharField(default='', max_length=200, verbose_name='Тип района')),
                ('formalname_area', models.CharField(default='', max_length=200, verbose_name='Район ')),
                ('shortname_city', models.CharField(default='', max_length=200, verbose_name='Тип населенного пункта')),
                ('formalname_city', models.CharField(default='', max_length=200, verbose_name='Населенный пункт')),
                ('shortname_street', models.CharField(default='', max_length=200, verbose_name='Тип улицы')),
                ('formalname_street', models.CharField(default='', max_length=200, verbose_name='Улица')),
                ('house_number', models.IntegerField(blank=True, null=True, verbose_name='Номер дома')),
                ('building', models.IntegerField(blank=True, null=True, verbose_name='Строение')),
                ('block', models.IntegerField(blank=True, null=True, verbose_name='Корпус')),
                ('letter', models.CharField(default='', max_length=200, verbose_name='Литера')),
                ('address', models.CharField(default='', max_length=200, verbose_name='Адрес дома')),
                ('houseguid', models.IntegerField(blank=True, null=True, verbose_name='Глобальный уникальный идентификатор дома')),
                ('built_year', models.IntegerField(blank=True, null=True, verbose_name='Год постройки')),
                ('exploitation_start_year', models.IntegerField(blank=True, null=True, verbose_name='Год ввода в эксплуатацию')),
                ('project_type', models.CharField(default='', max_length=200, verbose_name='Серия, тип постройки здания')),
                ('house_type', models.CharField(default='', max_length=200, verbose_name='Тип дома')),
                ('is_alarm', models.NullBooleanField(verbose_name='Факт признания дома аварийным')),
                ('management_organization_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_req.ManagingOrganization', verbose_name='ID Управляющей организации на Портале')),
            ],
        ),
        migrations.CreateModel(
            name='UserReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(default='', max_length=200, verbose_name='Фамилия')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Имя')),
                ('patronymic', models.CharField(default='', max_length=200, verbose_name='Отчество')),
                ('email', models.CharField(default='', max_length=200, verbose_name='Почта')),
                ('phone', models.CharField(default='', max_length=200, verbose_name='Номер телефона')),
                ('address', models.CharField(default='', max_length=200, verbose_name='Адрес')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='user_req',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_req.UserReq', verbose_name='UserInfo'),
        ),
    ]
