# Generated by Django 2.2.3 on 2019-07-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_req', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectstructure',
            name='built_year',
        ),
        migrations.RemoveField(
            model_name='subjectstructure',
            name='exploitation_start_year',
        ),
        migrations.AddField(
            model_name='request',
            name='address_fias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='address_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subjectstructure',
            name='area_id',
            field=models.CharField(default='', max_length=200, verbose_name='Район (код ФИАС)'),
        ),
        migrations.AlterField(
            model_name='subjectstructure',
            name='block',
            field=models.CharField(default='', max_length=200, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='subjectstructure',
            name='building',
            field=models.CharField(default='', max_length=200, verbose_name='Строение'),
        ),
        migrations.AlterField(
            model_name='subjectstructure',
            name='city_id',
            field=models.CharField(default='', max_length=200, verbose_name='Населенный пункт (код ФИАС)'),
        ),
        migrations.AlterField(
            model_name='subjectstructure',
            name='house_number',
            field=models.CharField(default='', max_length=200, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='subjectstructure',
            name='houseguid',
            field=models.CharField(default='', max_length=200, verbose_name='Глобальный уникальный идентификатор дома'),
        ),
        migrations.AlterField(
            model_name='subjectstructure',
            name='is_alarm',
            field=models.CharField(default='', max_length=200, verbose_name='Факт признания дома аварийным'),
        ),
        migrations.AlterField(
            model_name='subjectstructure',
            name='region_id',
            field=models.CharField(default='', max_length=200, verbose_name='Субъект РФ (код ФИАС)'),
        ),
        migrations.AlterField(
            model_name='subjectstructure',
            name='street_id',
            field=models.CharField(default='', max_length=200, verbose_name='Улица (код ФИАС)'),
        ),
    ]
