# Generated by Django 2.2.3 on 2019-07-28 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_req', '0002_auto_20190728_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_fias', models.CharField(blank=True, max_length=100, null=True)),
                ('address_text', models.CharField(blank=True, max_length=100, null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_req.CategoryReq')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='smart_req.Problem'),
            preserve_default=False,
        ),
    ]
