# Generated by Django 2.2.3 on 2019-07-28 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_req', '0003_auto_20190728_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_req.Problem'),
        ),
    ]
